### ISSUE TITLE
incorrect placing of popover 

### ISSUE THREAD

**Issue by binson143** [maxisam/ngx-mat-popover#1]
actually this popover positioning incorrectly if the view port (visible area) height < popover height

See this.
https://stackblitz.com/edit/github-jfqzgu

**Expected**: Popover should render below of button due to its configuration & has enough space to accommodate the popover ( yes need some scrolling)

**Actual** Popover changing its yPos and rendering above of the button

Note: This might be an issue by material 'cdk-overlay-connected-position-bounding-box '   , incorrectly computing the box-model values..

Any suggestions would be appreciated.

**Comment by maxisam** [comment]
I think you need to check with Material team. I merely make it look like a popover. And you might wanna post this on StackOverflow as well.
